version: '3.8'

services:
  advert-service-db:
    image: postgres:latest
    container_name: chat_service_db
    environment:
      POSTGRES_USER: ${CHAT_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CHAT_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CHAT_SERVICE_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
